package com.java8Features.streamsQuestions;


import java.util.stream.Stream;

public class Example9 {

    public static void main(String[] args) {

//        Stream.iterate() in Java is a method used to create an infinite sequential ordered stream where each element is
//        generated by applying a function to the previous element. This method takes two parameters:
//        Seed: The initial value to start generating elements.
//        Function: A function that generates the next element based on the previous element.
//        Fibonacci series
        System.out.println("Fibonacci series");
        Stream.iterate(new int[] {0, 1},f -> new int[] {f[1], f[0]+f[1]}).limit(10).map(f->f[0]).forEach(s-> System.out.print(s+" "));

//        First 10 odd numbers
        System.out.println("");
        System.out.println("First 10 odd numbers");
        Stream.iterate(1,n->n+2).limit(10).forEach(s-> System.out.print(s+" "));

    }
}
